language: python

sudo: false

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran

before_install:
  - pip install -U pip setuptools wheel

install:
  - pip install -r requirements_test.txt
  - pip install codecov

script:
  - coverage run --source=FukuML setup.py test
  - pep8 FukuML/*.py --ignore=E501

after_success:
  - codecov

notifications:
  email:
    - fukuball@gmail.com